[msg MSG_SYUKAI_CHECK_001_2]
[s]Would you like to carry over[n]all of your cleared save data?[n][w][e]

[msg MSG_SYUKAI_CHECK_002]
[s]You will now carry over all of[n]your cleared save data and start the game.[n][w][e]

[msg MSG_SYUKAI_CHECK_003]
[s]Would you like to carry[n]over your cleared save data[n]according to your Customizable NG+ configuration?[n][w][e]

[msg MSG_SYUKAI_CHECK_004]
[s]The game will start with[n]carrying over saved clear data[n]according to your Customizable NG+ configuration.[n][w][e]